// <auto-generated />
using EFCoreDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreDemo.Migrations
{
    [DbContext(typeof(HardwareStoreContext))]
    [Migration("20260303192122_InitialSeed")]
    partial class InitialSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EFCoreDemo.Models.Brand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "DeWalt"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Milwaukee"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Makita"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Bosch"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Ryobi"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Craftsman"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Ridgid"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Black+Decker"
                        });
                });

            modelBuilder.Entity("EFCoreDemo.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Hand Tools"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Power Drills"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Saws"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Sanders & Grinders"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Measuring Tools"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Fastening Tools"
                        });
                });

            modelBuilder.Entity("EFCoreDemo.Models.Tool", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BrandID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("ID");

                    b.HasIndex("BrandID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Tools");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BrandID = 1,
                            CategoryID = 1,
                            Name = "Claw Hammer 16oz",
                            Price = 24.989999999999998
                        },
                        new
                        {
                            ID = 2,
                            BrandID = 2,
                            CategoryID = 1,
                            Name = "Claw Hammer 20oz",
                            Price = 34.990000000000002
                        },
                        new
                        {
                            ID = 3,
                            BrandID = 6,
                            CategoryID = 1,
                            Name = "Adjustable Wrench",
                            Price = 19.989999999999998
                        },
                        new
                        {
                            ID = 4,
                            BrandID = 4,
                            CategoryID = 1,
                            Name = "Pliers Set (3-piece)",
                            Price = 39.990000000000002
                        },
                        new
                        {
                            ID = 5,
                            BrandID = 8,
                            CategoryID = 1,
                            Name = "Screwdriver Set (8-piece)",
                            Price = 29.989999999999998
                        },
                        new
                        {
                            ID = 6,
                            BrandID = 5,
                            CategoryID = 1,
                            Name = "Utility Knife Folding",
                            Price = 14.99
                        },
                        new
                        {
                            ID = 7,
                            BrandID = 1,
                            CategoryID = 2,
                            Name = "20V Cordless Drill/Driver",
                            Price = 129.0
                        },
                        new
                        {
                            ID = 8,
                            BrandID = 2,
                            CategoryID = 2,
                            Name = "M18 Fuel Hammer Drill",
                            Price = 229.0
                        },
                        new
                        {
                            ID = 9,
                            BrandID = 3,
                            CategoryID = 2,
                            Name = "18V LXT Brushless Drill",
                            Price = 189.0
                        },
                        new
                        {
                            ID = 10,
                            BrandID = 4,
                            CategoryID = 2,
                            Name = "18V Compact Drill",
                            Price = 99.0
                        },
                        new
                        {
                            ID = 11,
                            BrandID = 5,
                            CategoryID = 2,
                            Name = "ONE+ 18V Cordless Drill",
                            Price = 79.0
                        },
                        new
                        {
                            ID = 12,
                            BrandID = 1,
                            CategoryID = 3,
                            Name = "7-1/4 Circular Saw",
                            Price = 149.0
                        },
                        new
                        {
                            ID = 13,
                            BrandID = 2,
                            CategoryID = 3,
                            Name = "M18 Fuel Circular Saw 7-1/4",
                            Price = 279.0
                        },
                        new
                        {
                            ID = 14,
                            BrandID = 3,
                            CategoryID = 3,
                            Name = "6-1/2 Circular Saw Compact",
                            Price = 119.0
                        },
                        new
                        {
                            ID = 15,
                            BrandID = 4,
                            CategoryID = 3,
                            Name = "Jigsaw Variable Speed",
                            Price = 89.989999999999995
                        },
                        new
                        {
                            ID = 16,
                            BrandID = 5,
                            CategoryID = 3,
                            Name = "Reciprocating Saw 18V",
                            Price = 129.0
                        },
                        new
                        {
                            ID = 17,
                            BrandID = 1,
                            CategoryID = 4,
                            Name = "Random Orbital Sander",
                            Price = 79.989999999999995
                        },
                        new
                        {
                            ID = 18,
                            BrandID = 2,
                            CategoryID = 4,
                            Name = "M18 Orbital Sander",
                            Price = 149.0
                        },
                        new
                        {
                            ID = 19,
                            BrandID = 4,
                            CategoryID = 4,
                            Name = "4-1/2 Angle Grinder",
                            Price = 69.989999999999995
                        },
                        new
                        {
                            ID = 20,
                            BrandID = 3,
                            CategoryID = 4,
                            Name = "Cordless Angle Grinder 18V",
                            Price = 119.0
                        },
                        new
                        {
                            ID = 21,
                            BrandID = 1,
                            CategoryID = 5,
                            Name = "25ft Tape Measure",
                            Price = 19.989999999999998
                        },
                        new
                        {
                            ID = 22,
                            BrandID = 4,
                            CategoryID = 5,
                            Name = "Laser Distance Measurer 165ft",
                            Price = 89.989999999999995
                        },
                        new
                        {
                            ID = 23,
                            BrandID = 6,
                            CategoryID = 5,
                            Name = "Digital Caliper",
                            Price = 39.990000000000002
                        },
                        new
                        {
                            ID = 24,
                            BrandID = 1,
                            CategoryID = 6,
                            Name = "Impact Driver 20V",
                            Price = 149.0
                        },
                        new
                        {
                            ID = 25,
                            BrandID = 2,
                            CategoryID = 6,
                            Name = "M18 Fuel Impact Driver",
                            Price = 199.0
                        },
                        new
                        {
                            ID = 26,
                            BrandID = 3,
                            CategoryID = 6,
                            Name = "Brad Nailer 18Ga Cordless",
                            Price = 269.0
                        },
                        new
                        {
                            ID = 27,
                            BrandID = 5,
                            CategoryID = 6,
                            Name = "18V Cordless Stapler",
                            Price = 99.0
                        });
                });

            modelBuilder.Entity("EFCoreDemo.Models.Tool", b =>
                {
                    b.HasOne("EFCoreDemo.Models.Brand", "Brand")
                        .WithMany("Tools")
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreDemo.Models.Category", "Category")
                        .WithMany("Tools")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EFCoreDemo.Models.Brand", b =>
                {
                    b.Navigation("Tools");
                });

            modelBuilder.Entity("EFCoreDemo.Models.Category", b =>
                {
                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
